#!/usr/bin/env bash

for i in {1..100}
do
    echo $i
done

for (( i=1; i<=10; i++ ))
do
    echo $i
done

declare -a fruits=("apple" "banana" "cherry")
for i in ${fruits[@]}
do
    echo $i
done

declare -A arr
arr["name"]="Ryan"
arr["id"]="1234"

for i in "${!arr[@]}"
do
    echo $i: "${arr[$i]}"
done

for i in *
do
    echo "Found a file: $i"
done