#!/usr/bin/env bash
<<com
read -ep "Favorite color? " -i "Blue" favcolor
echo "$favcolor"


if (($#<3)); then
  echo "This command requires three arguments:"
  echo "username, userid, and favorite number"
else
  echo "username: $1"
  echo "userid: $2"
  echo "favorite number: $3"
fi

read -p "Favorite animal? " fav
while [[ -z $fav ]]
do
    read -p  "I need an answer! " fav
done
echo "$fav was selected."

read -p "Favorite animal? [cat] " fav
if [[ -z $fav ]]; then
    fav="cat"
fi
echo "$fav was selected."

com

read -p "What year? [nnnn] " year
until  [[ $year =~ [0-9]{4} ]]; do
    read -p "A four-digit year, please! [nnnn] " year
done
echo "Selected year: $year"